nome = str(input('Qual o seu nome completo? ')).strip()
n = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(n[0]))
print('Seu úlitmo nome é {}'.format(n[len(n)-1]))